# Generated by Django 4.2.16 on 2025-01-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_coletafaces_created_at_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='dataHora',
            field=models.DateTimeField(auto_now_add=True, default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto/'),
        ),
    ]
