# Generated by Django 4.2.16 on 2025-01-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_funcionario_datahora_alter_funcionario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coletafaces',
            name='created_at',
            field=models.DateTimeField(default=True),
        ),
    ]
