# Generated by Django 4.2.16 on 2025-01-29 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_coletafaces_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='observacao',
            field=models.CharField(default='Sem Observacao', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coletafaces',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dataHora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
