# Generated by Django 4.2.16 on 2025-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_funcionario_observacao_alter_coletafaces_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletafaces',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
