# Generated by Django 4.2.16 on 2025-09-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_coletafaces_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='foto',
        ),
        migrations.AlterField(
            model_name='coletafaces',
            name='observacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='observacao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
