# Generated by Django 4.2.16 on 2025-09-22 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_remove_funcionario_foto_alter_coletafaces_observacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gabinete', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.funcionario')),
            ],
        ),
    ]
