# Generated by Django 4.2.16 on 2025-09-25 10:44

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_registroentrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=11)),
        ),
    ]
