# Generated by Django 4.2.16 on 2025-09-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_funcionario_cpf_hash_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf_hash',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
