# Generated by Django 4.2.16 on 2025-09-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_remove_funcionario_cpf_hash_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dataHora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
